var dir_134b3b942a982a2b2c129f0b3730635b =
[
    [ "detail", "dir_bc09294f8086181796c3f54f48d8932c.html", "dir_bc09294f8086181796c3f54f48d8932c" ],
    [ "apply.hpp", "apply_8hpp.html", "apply_8hpp" ],
    [ "apply.t.cpp", "apply_8t_8cpp.html", "apply_8t_8cpp" ],
    [ "comonad.hpp", "comonad_8hpp.html", "comonad_8hpp" ],
    [ "comonad.t.cpp", "comonad_8t_8cpp.html", "comonad_8t_8cpp" ],
    [ "dual_monoid.hpp", "dual__monoid_8hpp.html", "dual__monoid_8hpp" ],
    [ "dual_monoid.t.cpp", "dual__monoid_8t_8cpp.html", "dual__monoid_8t_8cpp" ],
    [ "either.hpp", "either_8hpp.html", "either_8hpp" ],
    [ "either.t.cpp", "either_8t_8cpp.html", "either_8t_8cpp" ],
    [ "fold.hpp", "fold_8hpp.html", "fold_8hpp" ],
    [ "fold.t.cpp", "fold_8t_8cpp.html", "fold_8t_8cpp" ],
    [ "functor.hpp", "functor_8hpp.html", "functor_8hpp" ],
    [ "functor.t.cpp", "functor_8t_8cpp.html", "functor_8t_8cpp" ],
    [ "identity.hpp", "identity_8hpp.html", "identity_8hpp" ],
    [ "identity.t.cpp", "identity_8t_8cpp.html", "identity_8t_8cpp" ],
    [ "monad.hpp", "monad_8hpp.html", "monad_8hpp" ],
    [ "monad.t.cpp", "monad_8t_8cpp.html", "monad_8t_8cpp" ],
    [ "monoid.hpp", "monoid_8hpp.html", "monoid_8hpp" ],
    [ "monoid.t.cpp", "monoid_8t_8cpp.html", "monoid_8t_8cpp" ],
    [ "pair.hpp", "pair_8hpp.html", "pair_8hpp" ],
    [ "pair.t.cpp", "pair_8t_8cpp.html", "pair_8t_8cpp" ],
    [ "sequence.hpp", "sequence_8hpp.html", "sequence_8hpp" ],
    [ "sequence.t.cpp", "sequence_8t_8cpp.html", "sequence_8t_8cpp" ],
    [ "test_support.hpp", "test__support_8hpp.html", "test__support_8hpp" ],
    [ "traverse.hpp", "traverse_8hpp.html", "traverse_8hpp" ],
    [ "traverse.t.cpp", "traverse_8t_8cpp.html", "traverse_8t_8cpp" ]
];